--Drones
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1001, 100, 'Lightweight', '123456789A', 'IDLE', 200, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1002, 100, 'Lightweight', '123456789A', 'IDLE', 200, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1003, 100, 'Middleweight', '123456789B', 'IDLE', 300, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1004, 80, 'Middleweight', '123456789B', 'IDLE', 300, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1005, 98, 'Middleweight', '123456789B', 'IDLE', 300, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1006, 75, 'Cruiserweight', '123456789C', 'IDLE', 400, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1007, 100, 'Cruiserweight', '123456789C', 'IDLE', 400, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1008, 50, 'Heavyweight', '123456789D', 'IDLE', 500, 0);
INSERT INTO DRONE (ID, BATTERY_CAPACITY, MODEL,	SERIAL_NUMBER, STATE, WEIGHT_LIMIT, WEIGHT_LOAD) VALUES (1009, 20, 'Heavyweight', '123456789D', 'IDLE', 500, 0);

--Medication
INSERT INTO MEDICATION (ID, CODE, IMAGE, NAME, WEIGHT) VALUES (6001, 'MED01', 'https://mydrones.blob.core.windows.net/devices/medication/Acetaminophen.jpg', 'Acetaminophen', 60);
INSERT INTO MEDICATION (ID, CODE, IMAGE, NAME, WEIGHT) VALUES (6002, 'MED02', 'https://mydrones.blob.core.windows.net/devices/medication/Amoxicillin.jpg', 'Amoxicillin', 50);
INSERT INTO MEDICATION (ID, CODE, IMAGE, NAME, WEIGHT) VALUES (6003, 'MED03', 'https://mydrones.blob.core.windows.net/devices/medication/Ciprofloxacin.jpg', 'Ciprofloxacin', 30);
INSERT INTO MEDICATION (ID, CODE, IMAGE, NAME, WEIGHT) VALUES (6004, 'MED04', 'https://mydrones.blob.core.windows.net/devices/medication/Loratadine.jpg', 'Loratadine', 20);
INSERT INTO MEDICATION (ID, CODE, IMAGE, NAME, WEIGHT) VALUES (6005, 'MED05', 'https://mydrones.blob.core.windows.net/devices/medication/Tramadol.jpg', 'Tramadol', 70);